### ISSUE TITLE
Hot-Reloading

### ISSUE THREAD

**Issue by Equanox** [benchkram/bob#240]
Gathering infos on how hot reloading works for most common frameworks in the javascript ecosystem.

- [x] Vue - stores files in `node_modules/.cache`
- [x] Svelte - uses Vite - stores files in `node_modules/.vite` 
- [x] React - `node_modules/.cache`
- [ ] Node.js (express.js or other)
- [ ] nodemon.io

 
**Unrelated**
- [x] turborepo - stores cache artifacts in `node_modules/.cache`

**Possible Solutions:**
1. Using `mv` to restore targets
2. Introduce target diffing and ignore `node_modules/.cache` entirely

**Comment by zuzuleinen** [comment]
### Context of the issue we are facing

For some version of vue, having a build task like:

```yaml
  build:
    input: |
      package.json
      package-lock.json
    cmd: npm ci
    target: node_modules/
```

If you run `bob build` and then start the local server in a separate tab with `npm run dev`, if you run `bob build` again will kill the running server because bob will rebuild and replace ` node_modules/` target with the newly created artifact.

The reason for this is that the `npm run dev` creates a `.cache` directory inside node_modules/ and bob will see that as invalid target and will attempt to rebuild and replace node modules with latest artifact.

### Other solution

If nothing has changed from inputs, don't try to rebuild again. Optionally, show that the target has been tampered with.

**Reason**: 

I see the build task as an impure function. Giving some inputs, the function returns same result every time you run it. If inputs change, then the function returns a different result(in our case target).

```shell
                             inputs -----> build() -------------> result
```

We are here in a situation where the user changes that result, and because of that we attempt to rebuild breaking running process of the user. Why do we do that? We should attempt to rebuild only if inputs change. And in this case neither  `package.json` nor `package-lock.json` have changed. 

A build system should help the user build a result. What he does with that result its up to him. This is not only about JS frameworks, but a general case: if I build something I should do whatever I want with that result. The build system should not come to attempt and tamper with my modified result in any way. 

### A discussion for another time:

Maybe we need a different abastraction for targets which should provide a general solution which should avoid these kinds of problems. Maybe a target should not be mapped to a file, but something else. For example, if inputs change and a new result is generated, for a file target, we replace that file. Why not create a different file and leave the previous one alone? This will avoid the problem we have above for example. 

Now we have target files, directories and images. Maybe we can come up with a different abastraction that will help the user reason about them in an intuitive way.  Anyway, this is just food for thought for later. Feel free to ignore this section.

**Comment by rdnt** [comment]
It's actually tooling around the UI frameworks that affects what goes into node_modules and forces the cached entry to be used.

Webpack and eslint for example use a `.cache` directory inside node_modules
Projects using Vite have a `.vite` inside node_modules.

My suggestions are the following:
- UI dev servers don't like when files change one by one, directory renaming should be used as often as possible.
- In the cases mentioned above, it is clear that we need to allow for a user to specify a target much like they specify inputs; being able to ignore specific directories at their discretion.
- I don't think bob should explicitly handle these cases on its own. We should rather include a documentation entry for users of specific frameworks.

**Comment by Equanox** [comment]
"We are here in a situation where the user changes that result, and because of that we attempt to rebuild breaking running process of the user. Why do we do that?"
=> The intent is to assure the target on the filesystem is in a valid state. It seems we are too aggressive currently by removing the entire directory.

 "if I build something I should do whatever I want with that result. The build system should not come to attempt and tamper with my modified result in any way."
 => subsequent task can rely on a target, therefore it's necessary to assure its correctness.

**Comment by rdnt** [comment]
In addition to the file diffing proposal above, we can try to detect the smallest directories (those deeper in the file-tree) that had a file or sub-directory modified, and instead of extracting their contents file-by-file, we can extract the whole directory on a temporary location and use the `os.Rename()` function to move the entire directory in one go.

This should help alleviate some issues with hot-reloading as, once a dev-server notices that something was modified, when they try to re-traverse the filetree they will not see files missing or some files being partially written.

Atomicity of the move syscall is not guaranteed on all platforms so we maybe have to investigate the viability of this approach and/or provide a means for the user to configure the extraction method themselves (a good candidate to include in a user-wide `.bobconfig` file). In my tests on Ubuntu, using `mv` allowed for the devserver to properly notice the file-tree change and recover.
